[versions]
detekt = "1.20.0"
jacoco = "0.8.7"
junit = "5.8.2"
kotlin = "1.5.31"
slf4j = "1.8.0-beta4"

[libraries]
assertj-core = { module = "org.assertj:assertj-core", version = "3.22.0" }
equalsverifier = { module = "nl.jqno.equalsverifier:equalsverifier", version = "3.10" }
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
kotlin-logging = { module = "io.github.microutils:kotlin-logging", version = "2.1.21" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
dokka = { id = "org.jetbrains.dokka", version = "1.6.21" }
spotless = { id = "com.diffplug.spotless", version = "6.5.0" }
